### ISSUE TITLE
Meta: make it easy to contribute

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/tidyswirl#10]
Create:

- [x] guidance on how to contribute to Tidyswirl (CONTRIBUTING.md)
- [x] a code of conduct (CODE_OF_CONDUCT.md)
- [x] lesson templates for consistency (could add to CONTRIBUTING)

**Comment by matt-dray** [comment]
* Code of conduct closed with https://github.com/matt-dray/tidyswirl/commit/077301ca074bf3c762082244aebdbfff90b91f9e
* Contributing closed with https://github.com/matt-dray/tidyswirl/commit/7059d03f3966674515815ef462253a3b2cb7991e
* Lesson template closed with https://github.com/matt-dray/tidyswirl/commit/66fff0e04d27bf750bb17e28fcaf0aeece8a4393
