### ISSUE TITLE
Recommend swirl courses before tidyswirl

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/tidyswirl#2]
People should probably have done the following from the 'R Programming: The basics of programming in R' course:

- [x] 1: Basic Building Blocks
- [x] 2: Workspace and Files
- [x] 3: Sequences of Numbers
- [x] 4: Vectors
- [x] 5: Missing Values
- [x] 6: Subsetting Vectors
- [ ] 7: Matrices and Data Frames
- [ ] 8: Logic
- [ ] 9: Functions
- [ ] ~10: lapply and sapply~
- [ ] ~11: vapply and tapply~
- [ ] ~12: Looking at Data~
- [ ] ~13: Simulation~
- [ ] ~14: Dates and Times~
- [ ] ~15: Base Graphics~

**Comment by matt-dray** [comment]
Added to readme
